export const estados = [
    {'id': 1, 'nome' : 'Acre', 'Sigla' : 'AC'},
    {'id': 2, 'nome' : 'Alagoas', 'Sigla' : 'AL'},
    {'id': 3, 'nome' : 'Amapá', 'Sigla' : 'AP'},
    {'id': 4, 'nome' : 'Amazonas', 'Sigla' : 'AM'},
    {'id': 5, 'nome' : 'Bahia', 'Sigla' : 'BA'},
    {'id': 6, 'nome' : 'Ceará', 'Sigla' : 'CE'},
    {'id': 7, 'nome' : 'Espirito Santo', 'Sigla' : 'ES'},
    {'id': 8, 'nome' : 'Goiás', 'Sigla' : 'GO'},
    {'id': 9, 'nome' : 'Maranhão', 'Sigla' : 'MA'},
    {'id': 10, 'nome' : 'Mato Grosso', 'Sigla' : 'MT'},
    {'id': 11, 'nome' : 'Mato Grosso do Sul', 'Sigla' : 'MS'},
    {'id': 12, 'nome' : 'Minas Gerais', 'Sigla' : 'MG'},
    {'id': 13, 'nome' : 'Pará', 'Sigla' : 'PA'},
    {'id': 14, 'nome' : 'Paraíba', 'Sigla' : 'PB'},
    {'id': 15, 'nome' : 'Paraná', 'Sigla' : 'PR'},
    {'id': 16, 'nome' : 'Pernanbuco', 'Sigla' : 'PE'},
    {'id': 17, 'nome' : 'Piauí', 'Sigla' : 'PI'},
    {'id': 18, 'nome' : 'Rio de Janeiro', 'Sigla' : 'RJ'},
    {'id': 19, 'nome' : 'Rio Grande do Norte', 'Sigla' : 'RN'},
    {'id': 20, 'nome' : 'Rio Grande do Sul', 'Sigla' : 'RS'},
    {'id': 21, 'nome' : 'Rondônia', 'Sigla' : 'RO'},
    {'id': 22, 'nome' : 'Roraima', 'Sigla' : 'MA'},
    {'id': 23, 'nome' : 'Santa Catarina', 'Sigla' : 'SC'},
    {'id': 24, 'nome' : 'São Paulo', 'Sigla' : 'SP'},
    {'id': 25, 'nome' : 'Sergipe', 'Sigla' : 'SE'},
    {'id': 26, 'nome' : 'Tocantins', 'Sigla' : 'TO'},
    {'id': 27, 'nome' : 'Distrito Federal', 'Sigla' : 'DF'}
];